# github workflow to automate builds

name: Windows build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Visual Studio

    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install v141_xp toolset
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath`) do set VSPATH=%%i
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "%VSPATH%" --add Microsoft.VisualStudio.Component.WinXP --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP --quiet --norestart --nocache

      - name: Build
        shell: cmd
        working-directory: Steam
        run: MSBuild -m Steam.sln -t:Steam:Rebuild "-p:Configuration=Release" -p:Platform=Win32 -p:PlatformToolset=v141_xp

      - name: Build 2003 DLL
        shell: cmd
        working-directory: Steam
        run: MSBuild -m Steam.sln -t:Steam:Rebuild "-p:Configuration=Steam 2003" -p:Platform=Win32 -p:PlatformToolset=v141_xp

      - name: Prepare files for packaging
        shell: cmd
        run: |
          mkdir artifacts
          copy Steam\Release\Steam.dll artifacts\Steam.dll
          copy Steam\Release\Steam.pdb artifacts\Steam.pdb
          copy Steam\steam\rev.ini artifacts\rev.ini
          copy Steam\steam\revApps.ini artifacts\revApps.ini
          mkdir artifacts\2003
          copy Steam\Release_2003\Steam.dll artifacts\2003\Steam.dll
          copy Steam\Release_2003\Steam.pdb artifacts\2003\Steam.pdb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReviveEmu
          path: artifacts
          if-no-files-found: error
  create-release:
    name: Create release
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/

      - name: Display downloaded artifacts
        run: find ./artifacts/

      - name: Create release files
        run: |
          mkdir release
          pushd ./artifacts/
          for DIR in *; do
            pushd $DIR
            zip -r9 ../../release/$DIR.zip .
            popd
          done
          popd

      - name: Create rolling release
        if: github.ref == 'refs/heads/main'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest rolling release"
          files: |
            ./release/*
